title: trashnet.xyz
description: ugh!

url: https://trashnet.xyz
baseurl: ""

google_analytics: G-W7CF7M0QTY

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      category: articles

  - scope:
      path: journal
      type: posts
    values:
      layout: journal
      category: journal

  - scope:
      path: assets/images
    values:
      image: true

permalink: /:categories/:year:month:day:output_ext
